# Generated by Django 4.2.6 on 2023-10-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('class_or_school', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('tutor_name', models.CharField(max_length=100)),
                ('subjects', models.CharField(max_length=100)),
                ('starting_date', models.CharField(max_length=100)),
                ('fee', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=20)),
                ('sr_no', models.PositiveIntegerField(blank=True, default=0, null=True, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='StudentRecords',
        ),
    ]
