# Generated by Django 4.2.6 on 2023-10-11 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_studentrecord_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrecord',
            name='completion_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='starting_date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('fee_received', models.BooleanField(default=False)),
                ('fee', models.CharField(max_length=100)),
                ('received_date', models.DateField()),
                ('mode_of_payment', models.CharField(max_length=100)),
                ('receipt', models.CharField(max_length=100)),
                ('tutor_paid', models.BooleanField(default=False)),
                ('tutor_fee', models.CharField(max_length=100)),
                ('date_of_payment', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.studentrecord')),
            ],
        ),
    ]
