# Generated by Django 4.2.6 on 2023-10-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_studentrecord_completion_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='fee',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='detail',
            name='mode_of_payment',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='detail',
            name='receipt',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='detail',
            name='tutor_fee',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
