# Generated by Django 4.2.6 on 2023-10-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_detail_fee_alter_detail_mode_of_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecord',
            name='sr_no',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
