# Generated by Django 4.2.6 on 2023-10-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_studentrecord_sr_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecord',
            name='sr_no',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
