# Generated by Django 4.2.6 on 2023-10-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_studentrecord_sr_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='date_of_payment',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='due_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='received_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='start_date',
            field=models.DateField(blank=True),
        ),
    ]
